//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medics.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int IdPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
    }
}
